version: 2
jobs:
  build:
    working_directory: ~/bookstore
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: your-app-name
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: booktsore
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec
